---
- name: Include apache config vars
  include_vars:
    file: "{{ item }}"
  with_items:
    - configs/apache/apache_{{ app_env }}_{{ server_name }}.yml
    - vars/configs/apache/apache_maintenance.yml

- name: Create common directory
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/apache2/common

- name: Create apache maintenance file
  blockinfile:
    dest: /etc/apache2/common/apache.maintenance
    create: yes
    mode: 0644
    block: |
      {{ apache_maintenance }}

- name: Create apache disabled maintenance file
  blockinfile:
    dest: /etc/apache2/common/maintenance.html.disabled
    create: yes
    mode: 0644
    block: |
      {{ apache_maintenance_disabled }}

- name: Create local app1 apache config
  blockinfile:
    dest: /etc/apache2/sites-available/app1.conf
    create: yes
    mode: 0644
    block: |
      {{ apache_the_app1 }}

- name: Create local app2 apache config
  blockinfile:
    dest: /etc/apache2/sites-available/app2.conf
    create: yes
    mode: 0644
    block: |
      {{ apache_app2 }}

- name: Create local ssl rewrite apache config
  blockinfile:
    dest: /etc/apache2/sites-available/ssl_redirect.conf
    create: yes
    mode: 0644
    block: |
      {{ apache_ssl_redirect }}

- name: Enable rewrite module
  apache2_module:
    name: rewrite
    state: present

- name: Enable ssl module
  apache2_module:
    name: ssl
    state: present

- name: Disable default site
  shell: a2dissite 000-default

- name: Enable local apache sites
  shell: a2ensite {{ item }}.conf
  with_items:
    - <app1>
    - <app2>
    - ssl_redirect
