---
- name: Update and upgrade
  shell: apt-get update ; DEBIAN_FRONTEND=noninteractive apt-get upgrade -yq
  args:
    warn: no

- name: Config sudo permissions
  blockinfile:
    dest: /etc/sudoers
    block: |
      "{{ username | lower }}" ALL=(ALL:ALL) ALL
      "{{ username | lower }}" ALL=NOPASSWD: ALL
