---
- name: Install redis server
  apt:
    name: redis-server
    state: present

- name: Enable redis supervised mode
  replace:
    path: /etc/redis/redis.conf
    regexp: 'supervised no'
    replace: "supervised systemd"

- name: Start redis service
  service:
    name: redis-server
    state: restarted
