---
- name: Install docker dependencies
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common']
    state: present

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present
    update_cache: true

- name: Update cache
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce
    state: present

- name: Add user to docker group
  user:
    name: "{{ username | lower }}"
    groups: docker

- name: Start docker service
  service:
    name: docker
    state: restarted
