---
- name: Provision EC2 instance
  ec2:
    exact_count: "{{ count }}"
    profile: "{{ aws_profile }}"
    image: "{{ ami_id }}"
    instance_type: "{{ type }}"
    ec2_region: "{{ region }}"
    key_name: "{{ key_pair }}"
    group: "{{ group }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    wait: true
    wait_timeout: 500
    volumes:
    - device_name: /dev/sda1
      volume_size: "{{ ec2_volume_size }}"
    instance_tags:
      Name: "{{ instance_name }}"
      OS: "{{ operating_system }}"
      Host_Name: "{{ host_name | lower }}"
      Environment: "{{ app_env | upper }}"
    count_tag:
      Name: "{{ instance_name }}"
    monitoring: "{{ termination_protection }}"
    termination_protection: "{{ termination_protection }}"
  register: ec2

- name: Add instance to the host file
  local_action: lineinfile
                dest="./hosts"
                regexp={{ item.public_ip }}
                insertafter="[webserver]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Wait for ssh
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
  with_items: "{{ ec2.instances }}"

- name: Refresh hosts file
  meta: refresh_inventory
