---
- name: Include vars
  include_vars:
    file: vars/configs/ftp/vsftpd.yml

- name: Create fmftp user
  user:
    name: fmftp
    shell: /bin/bash
    groups: systemd-journal
    generate_ssh_key: yes
    password: "{{ ftp_user_pass }}"
    state: present

- name: Install vsftpd packages
  apt:
    name: vsftpd
    state: present

- name: Delete default vsftpd config
  file:
    dest: /etc/vsftpd.conf
    state: absent

- name: Edit vsftpd config
  blockinfile:
    dest: /etc/vsftpd.conf
    create: yes
    owner: root
    group: root
    block: |
      {{ vsftpd_conf }}

- name: Edit vsftpd chroot_list
  lineinfile:
    dest: /etc/vsftpd.chroot_list
    create: yes
    owner: root
    group: root
    line: fmftp

- name: Restart vsftpd service
  service:
    name: vsftpd
    state: restarted
