---
- name: Install mahout dependencies
  apt:
    name: ['mysql-client', 'libmysql-java', 'aptitude']
    state: present

- name: Create mahout directory
  file:
    dest: /usr/lib/mahout
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Check if mahout is installed
  stat:
    path: /home/{{ username }}/apache-mahout-distribution-0.11.1
  register: stat_result_mahout

- name: Download mahout
  get_url:
    url: https://archive.apache.org/dist/mahout/0.11.1/apache-mahout-distribution-0.11.1.tar.gz
    dest: /home/{{ username }}
  when: stat_result_mahout.stat.exists == False

- name: Unarchive mahout
  unarchive:
    src: /home/{{ username }}/apache-mahout-distribution-0.11.1.tar.gz
    remote_src: yes
    dest: /home/{{ username }}
  when: stat_result_mahout.stat.exists == False

- name: Delete mahout zip
  file:
    dest: /home/{{ username }}/apache-mahout-distribution-0.11.1.tar.gz
    state: absent

- name: Add mahout path
  lineinfile:
    path: /home/{{ username }}/.bashrc
    line: export MAHOUT_HOME=/usr/local/mahout
    state: present
