---
- name: Include motd config vars
  include_vars:
    file: configs/motd/motd_{{ app_env }}_{{ server_name }}.yml

- name: Remove default motd
  shell: rm /etc/update-motd.d/*
  args:
    warn: no

- name: Create motd
  blockinfile:
    dest: /etc/update-motd.d/10-motd
    create: yes
    owner: root
    group: root
    mode: 0755
    marker: ""
    block: |
      {{ motd }}

- name: Remove blank lines from motd
  lineinfile:
    path: /etc/update-motd.d/10-motd
    state: absent
    regexp: '^$'
