---
- name: Install the mysql packages
  apt:
    name: ['mysql-server', 'mysql-client', 'python-mysqldb', 'libmysqlclient-dev']
    state: installed
    update_cache: yes

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src: mysql/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql_server_password }}"
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Restart mysql-server
  service:
    name: mysql
    state: restarted

- name: Ensure Anonymous user are not in the database
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: Create casserver database
  mysql_db:
    name: casserver
    state: present

- name: Restart mysql-server
  service:
    name: mysql
    state: restarted
