---
- name: Uninstall prometheus
  apt:
    name: prometheus
    state: absent

- name: Extract node_exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Create node_exporter service
  blockinfile:
    path: /etc/systemd/system/node_exporter.service
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User={{ username }}
      ExecStart=/opt/node_exporter-0.16.0.linux-amd64/node_exporter

      [Install]
      WantedBy=default.target

- name: Reload services
  command: systemctl daemon-reload

- name: Start and enable node_exporter
  service:
    name: node_exporter
    state: restarted
    enabled: yes

- name: Add prometheus repo
  apt_key:
    url: https://s3-eu-west-1.amazonaws.com/deb.robustperception.io/41EFC99D.gpg
    state: present

- name: Update cache
  apt:
    update_cache: yes

- name: Install prometheus
  apt:
    name: prometheus
    state: present

- name: Enable and start prometheus
  service:
    name: prometheus
    state: restarted
    enabled: yes
