---
- name: Install rabbitmq
  apt:
    name: rabbitmq-server
    state: present

- name: Create rabbitmq bunny user
  rabbitmq_user:
    user: bunny
    password: "{{ rabbitmq_admin_password }}"
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Delete rabbitmq guest user
  rabbitmq_user:
    user: guest
    state: absent

- name: Enable plugin
  shell: rabbitmq-plugins enable rabbitmq_management

- name: Start rabbitmq service
  service:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Create rabbitmq datadog user
  rabbitmq_user:
    user: datadog
    password: "{{ rabbitmq_datadog_password }}"
    tags: monitoring
    configure_priv: ^aliveness-test$
    read_priv: ^amq\.default$
    write_priv: .*
    state: present
  tags: datadog
  when: app_env == "prod"
