---
- name: Include solr vars
  include_vars:
    file: configs/solr/solr_config.yml

- name: Check for solr tar
  stat:
    path: /opt/solr-{{ solr_version }}.tgz
  register: stat_result_solr_tar

- name: Download solr
  get_url:
    url: https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz
    dest: /opt/solr-{{ solr_version }}.tgz
  when: stat_result_solr_tar.stat.exists == False

- name: Check for solr unzipped
  stat:
    path: /opt/install_solr_service.sh
  register: stat_result_solr_unzip

- name: Extract solr
  shell: tar xzf solr-{{ solr_version }}.tgz solr-{{ solr_version }}/bin/install_solr_service.sh --strip-components=2
  args:
    chdir: /opt
    warn: no
  when: stat_result_solr_unzip.stat.exists == False

- name: Check for solr install
  stat:
    path: /etc/init.d/solr
  register: stat_result_solr_install

- name: Install solr
  shell: bash /opt/install_solr_service.sh solr-{{ solr_version }}.tgz
  args:
    chdir: /opt
  when: stat_result_solr_install.stat.exists == False

- name: Install mysql lib
  apt:
    name: ['libmysqlclient-dev', 'libmysql-java']
    state: present

- name: Check if solr us core exists
  stat:
    path: /var/solr/data/{{ app_env }}_us
  register: stat_result_solr_core_us
  become_user: solr

- name: Create stage solr us core
  command: /opt/solr/bin/solr create_core -c stage_us
  become_user: solr
  when: stat_result_solr_core_us.stat.exists == False and app_env == "stage"

- name: Create prod solr us core
  command: /opt/solr/bin/solr create_core -c prod_us
  become_user: solr
  when: stat_result_solr_core_us.stat.exists == False and server_name == "solr_us" and app_env == "prod"

- name: Check if solr uk core exists
  stat:
    path: /var/solr/data/{{ app_env }}_uk
  register: stat_result_solr_core_uk
  become_user: solr

- name: Create stage solr uk core
  command: /opt/solr/bin/solr create_core -c stage_uk
  become_user: solr
  when: stat_result_solr_core_uk.stat.exists == False and app_env == "stage"

- name: Create prod solr uk core
  command: /opt/solr/bin/solr create_core -c prod_uk
  become_user: solr
  when: stat_result_solr_core_uk.stat.exists == False and server_name == "solr_uk" and app_env == "prod"

- name: Protect from watchbog
  file:
    path: /bin/watchbog
    state: directory
    owner: root
    group: root
    mode: 1600

- name: Protect from watchbog
  file:
    path: /usr/bin/watchbog
    state: directory
    owner: root
    group: root
    mode: 1600

# - name: Restart solr service
#   service:
#     name: solr
#     state: restarted
#     enabled: yes
