---
- name: Update and upgrade
  shell: apt-get update ; DEBIAN_FRONTEND=noninteractive apt-get upgrade -yq
  args:
    warn: no

- name: Update cache
  apt:
    update_cache: yes

# - name: Restarting...
#   reboot:
